import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import BarChart from '@/components/barchart'
import PieChart from '@/components/piechart'
import DoughnutChart from '@/components/doughnutchart'




export default function Home() {
  return (
    <>
      <Head>
        <title>Chart Examples</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1>Statistics Canada Graphs</h1>
        <div className={styles.graphs}>
     
        <div className={styles.bar}>
        <h1 className={styles.headers}>Estimates of the components of natural increase, quarterly</h1>
        <BarChart/>
        </div>
        <div className={styles.pie}>
        <h1 className={styles.headers}>Monthly retail trade sales of motor vehicle and parts dealers, by industry (x 1,000)</h1>
        <PieChart/>
        </div>
        <div className={styles.doughnut}>
          <h1 className={styles.headers}>Monthly retail trade sales by industry (x 1,000)</h1>
        <DoughnutChart/>
        </div>
        </div>
       
      </main>
    </>
  )
}
